# Generated by Django 6.0.6 on 2026-06-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='career',
            new_name='carrier',
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
    ]
