# Generated by Django 6.0.6 on 2026-06-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_career_order_carrier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=20),
        ),
    ]
